"""initial_database_schema

Revision ID: e5aeb4074cfe
Revises:
Create Date: 2026-10-07 18:59:03.083149

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5aeb4074cfe"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "language",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "actor",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("first_name", sa.String(length=45), nullable=False),
        sa.Column("last_name", sa.String(length=45), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=25), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "country",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("country", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "city",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("city", sa.String(length=50), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["country_id"], ["country.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "film",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.Column("rental_duration", sa.Integer(), nullable=False),
        sa.Column("rental_rate", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("length", sa.Integer(), nullable=True),
        sa.Column("replacement_cost", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("rating", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["language_id"], ["language.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "address",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("address", sa.String(length=50), nullable=False),
        sa.Column("address2", sa.String(length=50), nullable=True),
        sa.Column("district", sa.String(length=20), nullable=False),
        sa.Column("postal_code", sa.String(length=10), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["city.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "staff",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("first_name", sa.String(length=45), nullable=False),
        sa.Column("last_name", sa.String(length=45), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("username", sa.String(length=16), nullable=False),
        sa.Column("password", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["address_id"], ["address.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "store",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["address_id"], ["address.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("staff", sa.Column("store_id", sa.Integer(), nullable=False))
    op.create_foreign_key("fk_staff_store", "staff", "store", ["store_id"], ["id"])
    op.add_column("store", sa.Column("manager_staff_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_store_manager", "store", "staff", ["manager_staff_id"], ["id"]
    )
    op.create_table(
        "customer",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=45), nullable=False),
        sa.Column("last_name", sa.String(length=45), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["address_id"], ["address.id"]),
        sa.ForeignKeyConstraint(["store_id"], ["store.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inventory",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("film_id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["film_id"], ["film.id"]),
        sa.ForeignKeyConstraint(["store_id"], ["store.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "film_actor",
        sa.Column("actor_id", sa.Integer(), nullable=False),
        sa.Column("film_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["actor.id"]),
        sa.ForeignKeyConstraint(["film_id"], ["film.id"]),
        sa.PrimaryKeyConstraint("actor_id", "film_id"),
    )
    op.create_table(
        "film_category",
        sa.Column("film_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"]),
        sa.ForeignKeyConstraint(["film_id"], ["film.id"]),
        sa.PrimaryKeyConstraint("film_id", "category_id"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("customer")
    op.drop_table("inventory")
    op.drop_table("film_category")
    op.drop_table("film_actor")
    op.drop_table("address")
    op.drop_table("film")
    op.drop_table("city")
    op.drop_table("store")
    op.drop_table("staff")
    op.drop_table("language")
    op.drop_table("country")
    op.drop_table("category")
    op.drop_table("actor")
    # ### end Alembic commands ###
